package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart")
public class Cart implements java.io.Serializable {

	private String cartId;
	private Product product;
	private UserProfile userProfile;
	private Integer quantity;
	private BigDecimal productCost;

	public Cart() {
	}

	public Cart(String cartId, Product product, UserProfile userProfile) {
		this.cartId = cartId;
		this.product = product;
		this.userProfile = userProfile;
	}

	public Cart(String cartId, Product product, UserProfile userProfile, Integer quantity, BigDecimal productCost) {
		this.cartId = cartId;
		this.product = product;
		this.userProfile = userProfile;
		this.quantity = quantity;
		this.productCost = productCost;
	}

	@Id

	@Column(name = "CART_ID", unique = true, nullable = false, length = 50)
	public String getCartId() {
		return this.cartId;
	}

	public void setCartId(String cartId) {
		this.cartId = cartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "QUANTITY")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "PRODUCT_COST", precision = 18, scale = 10)
	public BigDecimal getProductCost() {
		return this.productCost;
	}

	public void setProductCost(BigDecimal productCost) {
		this.productCost = productCost;
	}

}
