package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order")
public class Order implements java.io.Serializable {

	private String orderId;
	private PaymentStatus paymentStatus;
	private UserProfile userProfile;
	private String orderStatus;
	private String orderTrackingId;
	private Date orderDate;
	private OrderAddress orderAddress;
	private Set<Return> returns = new HashSet<Return>(0);

	public Order() {
	}

	public Order(String orderId, PaymentStatus paymentStatus, UserProfile userProfile) {
		this.orderId = orderId;
		this.paymentStatus = paymentStatus;
		this.userProfile = userProfile;
	}

	public Order(String orderId, PaymentStatus paymentStatus, UserProfile userProfile, String orderStatus,
			String orderTrackingId, Date orderDate, OrderAddress orderAddress, Set<Return> returns) {
		this.orderId = orderId;
		this.paymentStatus = paymentStatus;
		this.userProfile = userProfile;
		this.orderStatus = orderStatus;
		this.orderTrackingId = orderTrackingId;
		this.orderDate = orderDate;
		this.orderAddress = orderAddress;
		this.returns = returns;
	}

	@Id

	@Column(name = "ORDER_ID", unique = true, nullable = false, length = 50)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAYMENT_ID", nullable = false)
	public PaymentStatus getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(PaymentStatus paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "ORDER_STATUS", length = 45)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_TRACKING_ID", length = 45)
	public String getOrderTrackingId() {
		return this.orderTrackingId;
	}

	public void setOrderTrackingId(String orderTrackingId) {
		this.orderTrackingId = orderTrackingId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_DATE", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "order")
	public OrderAddress getOrderAddress() {
		return this.orderAddress;
	}

	public void setOrderAddress(OrderAddress orderAddress) {
		this.orderAddress = orderAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Return> getReturns() {
		return this.returns;
	}

	public void setReturns(Set<Return> returns) {
		this.returns = returns;
	}

}
