package com.tradeleaves.store.domain;
// Generated 30 Mar, 2016 6:51:48 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_details")
public class OrderDetails implements java.io.Serializable {

	private String orderId;
	private String paymentId;
	private String userId;
	private String orderStatus;
	private String orderTrackingId;
	private Date orderDate;

	public OrderDetails() {
	}

	public OrderDetails(String orderId, String paymentId, String userId) {
		this.orderId = orderId;
		this.paymentId = paymentId;
		this.userId = userId;
	}

	public OrderDetails(String orderId, String paymentId, String userId, String orderStatus, String orderTrackingId,
			Date orderDate) {
		this.orderId = orderId;
		this.paymentId = paymentId;
		this.userId = userId;
		this.orderStatus = orderStatus;
		this.orderTrackingId = orderTrackingId;
		this.orderDate = orderDate;
	}

	@Id

	@Column(name = "ORDER_ID", unique = true, nullable = false, length = 50)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "PAYMENT_ID", nullable = false, length = 50)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "USER_ID", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "ORDER_STATUS", length = 45)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_TRACKING_ID", length = 45)
	public String getOrderTrackingId() {
		return this.orderTrackingId;
	}

	public void setOrderTrackingId(String orderTrackingId) {
		this.orderTrackingId = orderTrackingId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_DATE", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
