package com.tradeleaves.store.domain;
// Generated 29 Mar, 2016 5:34:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductTerms generated by hbm2java
 */
@Entity
@Table(name = "product_terms")
public class ProductTerms implements java.io.Serializable {
	


	private String productTermId;
	private String productId;
	private String termName;
	private String termValue;

	public ProductTerms() {
	}

	public ProductTerms(String productTermId, String productId) {
		this.productTermId = productTermId;
		this.productId = productId;
	}

	public ProductTerms(String productTermId, String productId, String termName, String termValue) {
		this.productTermId = productTermId;
		this.productId = productId;
		this.termName = termName;
		this.termValue = termValue;
	}

	@Id

	@Column(name = "PRODUCT_TERM_ID", unique = true, nullable = false, length = 50)
	public String getProductTermId() {
		return this.productTermId;
	}

	public void setProductTermId(String productTermId) {
		this.productTermId = productTermId;
	}

	@Column(name = "PRODUCT_ID", nullable = false, length = 50)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "TERM_NAME", length = 45)
	public String getTermName() {
		return this.termName;
	}

	public void setTermName(String termName) {
		this.termName = termName;
	}

	@Column(name = "TERM_VALUE", length = 45)
	public String getTermValue() {
		return this.termValue;
	}

	public void setTermValue(String termValue) {
		this.termValue = termValue;
	}


}
