package com.tradeleaves.store.domain;
// Generated 29 Mar, 2016 5:34:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "product_attribute")
public class ProductAttribute implements java.io.Serializable {
	


	private String productAttributeId;
	private String productId;
	private String attributeName;
	private String attributeValue;

	public ProductAttribute() {
	}

	public ProductAttribute(String productAttributeId, String productId) {
		this.productAttributeId = productAttributeId;
		this.productId = productId;
	}

	public ProductAttribute(String productAttributeId, String productId, String attributeName, String attributeValue) {
		this.productAttributeId = productAttributeId;
		this.productId = productId;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
	}

	@Id

	@Column(name = "PRODUCT_ATTRIBUTE_ID", unique = true, nullable = false, length = 50)
	public String getProductAttributeId() {
		return this.productAttributeId;
	}

	public void setProductAttributeId(String productAttributeId) {
		this.productAttributeId = productAttributeId;
	}

	@Column(name = "PRODUCT_ID", nullable = false, length = 50)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "ATTRIBUTE_NAME", length = 45)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "ATTRIBUTE_VALUE", length = 45)
	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}


}
