package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * ProductTerms generated by hbm2java
 */
@Entity
@Table(name = "product_terms")
public class ProductTerms implements java.io.Serializable {

	private String productId;
	private Product product;
	private String productTermId;
	private String termName;
	private String termValue;

	public ProductTerms() {
	}

	public ProductTerms(Product product, String productTermId) {
		this.product = product;
		this.productTermId = productTermId;
	}

	public ProductTerms(Product product, String productTermId, String termName, String termValue) {
		this.product = product;
		this.productTermId = productTermId;
		this.termName = termName;
		this.termValue = termValue;
	}

//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "product") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "PRODUCT_ID", unique = true, nullable = false, length = 50)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "PRODUCT_TERM_ID", nullable = false, length = 50)
	public String getProductTermId() {
		return this.productTermId;
	}

	public void setProductTermId(String productTermId) {
		this.productTermId = productTermId;
	}

	@Column(name = "TERM_NAME", length = 45)
	public String getTermName() {
		return this.termName;
	}

	public void setTermName(String termName) {
		this.termName = termName;
	}

	@Column(name = "TERM_VALUE", length = 45)
	public String getTermValue() {
		return this.termValue;
	}

	public void setTermValue(String termValue) {
		this.termValue = termValue;
	}

}
