package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name = "product_attribute")
public class ProductAttribute implements java.io.Serializable {

	private String productId;
	private Product product;
	private String productAttributeId;
	private String attributeName;
	private String attributeValue;

	public ProductAttribute() {
	}

	public ProductAttribute(Product product, String productAttributeId) {
		this.product = product;
		this.productAttributeId = productAttributeId;
	}

	public ProductAttribute(Product product, String productAttributeId, String attributeName, String attributeValue) {
		this.product = product;
		this.productAttributeId = productAttributeId;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
	}

//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "product") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "PRODUCT_ID", unique = true, nullable = false, length = 50)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "PRODUCT_ATTRIBUTE_ID", nullable = false, length = 50)
	public String getProductAttributeId() {
		return this.productAttributeId;
	}

	public void setProductAttributeId(String productAttributeId) {
		this.productAttributeId = productAttributeId;
	}

	@Column(name = "ATTRIBUTE_NAME", length = 45)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "ATTRIBUTE_VALUE", length = 45)
	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

}
