package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReturnRefund generated by hbm2java
 */
@Entity
@Table(name = "return_refund")
public class ReturnRefund implements java.io.Serializable {

	private String returnRefundId;
	private String returnId;
	private String userId;
	private String refundStatus;
	private Date refundDate;

	public ReturnRefund() {
	}

	public ReturnRefund(String returnRefundId, String returnId, String userId) {
		this.returnRefundId = returnRefundId;
		this.returnId = returnId;
		this.userId = userId;
	}

	public ReturnRefund(String returnRefundId, String returnId, String userId, String refundStatus, Date refundDate) {
		this.returnRefundId = returnRefundId;
		this.returnId = returnId;
		this.userId = userId;
		this.refundStatus = refundStatus;
		this.refundDate = refundDate;
	}

	@Id

	@Column(name = "RETURN_REFUND_ID", unique = true, nullable = false, length = 50)
	public String getReturnRefundId() {
		return this.returnRefundId;
	}

	public void setReturnRefundId(String returnRefundId) {
		this.returnRefundId = returnRefundId;
	}

	@Column(name = "RETURN_ID", nullable = false, length = 50)
	public String getReturnId() {
		return this.returnId;
	}

	public void setReturnId(String returnId) {
		this.returnId = returnId;
	}

	@Column(name = "USER_ID", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "REFUND_STATUS", length = 45)
	public String getRefundStatus() {
		return this.refundStatus;
	}

	public void setRefundStatus(String refundStatus) {
		this.refundStatus = refundStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REFUND_DATE", length = 19)
	public Date getRefundDate() {
		return this.refundDate;
	}

	public void setRefundDate(Date refundDate) {
		this.refundDate = refundDate;
	}

}
