package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Return generated by hbm2java
 */
@Entity
@Table(name = "return")
public class Return implements java.io.Serializable {

	private String returnId;
	private Order order;
	private UserProfile userProfile;
	private String returnStatus;
	private Date returnDate;
	private Set<ReturnRefund> returnRefunds = new HashSet<ReturnRefund>(0);

	public Return() {
	}

	public Return(String returnId, Order order, UserProfile userProfile) {
		this.returnId = returnId;
		this.order = order;
		this.userProfile = userProfile;
	}

	public Return(String returnId, Order order, UserProfile userProfile, String returnStatus, Date returnDate,
			Set<ReturnRefund> returnRefunds) {
		this.returnId = returnId;
		this.order = order;
		this.userProfile = userProfile;
		this.returnStatus = returnStatus;
		this.returnDate = returnDate;
		this.returnRefunds = returnRefunds;
	}

	@Id

	@Column(name = "RETURN_ID", unique = true, nullable = false, length = 50)
	public String getReturnId() {
		return this.returnId;
	}

	public void setReturnId(String returnId) {
		this.returnId = returnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "RETURN_STATUS", length = 45)
	public String getReturnStatus() {
		return this.returnStatus;
	}

	public void setReturnStatus(String returnStatus) {
		this.returnStatus = returnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RETURN_DATE", length = 19)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "return")
	public Set<ReturnRefund> getReturnRefunds() {
		return this.returnRefunds;
	}

	public void setReturnRefunds(Set<ReturnRefund> returnRefunds) {
		this.returnRefunds = returnRefunds;
	}

}
