package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Return generated by hbm2java
 */
@Entity
@Table(name = "return")
public class Return implements java.io.Serializable {

	private String returnId;
	private String orderId;
	private String userId;
	private String returnStatus;
	private Date returnDate;

	public Return() {
	}

	public Return(String returnId, String orderId, String userId) {
		this.returnId = returnId;
		this.orderId = orderId;
		this.userId = userId;
	}

	public Return(String returnId, String orderId, String userId, String returnStatus, Date returnDate) {
		this.returnId = returnId;
		this.orderId = orderId;
		this.userId = userId;
		this.returnStatus = returnStatus;
		this.returnDate = returnDate;
	}

	@Id

	@Column(name = "RETURN_ID", unique = true, nullable = false, length = 50)
	public String getReturnId() {
		return this.returnId;
	}

	public void setReturnId(String returnId) {
		this.returnId = returnId;
	}

	@Column(name = "ORDER_ID", nullable = false, length = 50)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "USER_ID", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "RETURN_STATUS", length = 45)
	public String getReturnStatus() {
		return this.returnStatus;
	}

	public void setReturnStatus(String returnStatus) {
		this.returnStatus = returnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RETURN_DATE", length = 19)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

}
