package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAddress generated by hbm2java
 */
@Entity
@Table(name = "user_address")
public class UserAddress implements java.io.Serializable {

	private UserAddressId id;
	private UserProfile userProfile;
	private String addressLine1;
	private String adderssLine2;
	private String landMark;
	private String streetName;
	private String city;
	private String state;
	private Integer postalCode;

	public UserAddress() {
	}

	public UserAddress(UserAddressId id, UserProfile userProfile) {
		this.id = id;
		this.userProfile = userProfile;
	}

	public UserAddress(UserAddressId id, UserProfile userProfile, String addressLine1, String adderssLine2,
			String landMark, String streetName, String city, String state, Integer postalCode) {
		this.id = id;
		this.userProfile = userProfile;
		this.addressLine1 = addressLine1;
		this.adderssLine2 = adderssLine2;
		this.landMark = landMark;
		this.streetName = streetName;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "addressId", column = @Column(name = "ADDRESS_ID", nullable = false, length = 50) ),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false) ) })
	public UserAddressId getId() {
		return this.id;
	}

	public void setId(UserAddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "ADDRESS_LINE1")
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDERSS_LINE2")
	public String getAdderssLine2() {
		return this.adderssLine2;
	}

	public void setAdderssLine2(String adderssLine2) {
		this.adderssLine2 = adderssLine2;
	}

	@Column(name = "LAND_MARK", length = 60)
	public String getLandMark() {
		return this.landMark;
	}

	public void setLandMark(String landMark) {
		this.landMark = landMark;
	}

	@Column(name = "STREET_NAME", length = 45)
	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "POSTAL_CODE")
	public Integer getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(Integer postalCode) {
		this.postalCode = postalCode;
	}

}
