package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name = "user_login")
public class UserLogin implements java.io.Serializable {

	private String userId;
	private UserProfile userProfile;
	private String password;

	public UserLogin() {
	}

	public UserLogin(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	public UserLogin(UserProfile userProfile, String password) {
		this.userProfile = userProfile;
		this.password = password;
	}

//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userProfile") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "USER_ID", unique = true, nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "PASSWORD", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
