package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile")
public class UserProfile implements java.io.Serializable {

	private String userId;
	private String firstName;
	private String lastName;
	private String emailId;
	private String contactNumber;
	private Set<Return> returns = new HashSet<Return>(0);
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<UserAddress> userAddresses = new HashSet<UserAddress>(0);
	private UserLogin userLogin;
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<ReturnRefund> returnRefunds = new HashSet<ReturnRefund>(0);
	private Set<PaymentStatus> paymentStatuses = new HashSet<PaymentStatus>(0);
	private Set<OrderHistory> orderHistories = new HashSet<OrderHistory>(0);

	public UserProfile() {
	}

	public UserProfile(String userId) {
		this.userId = userId;
	}

	public UserProfile(String userId, String firstName, String lastName, String emailId, String contactNumber,
			Set<Return> returns, Set<Order> orders, Set<UserAddress> userAddresses, UserLogin userLogin,
			Set<Cart> carts, Set<ReturnRefund> returnRefunds, Set<PaymentStatus> paymentStatuses,
			Set<OrderHistory> orderHistories) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.contactNumber = contactNumber;
		this.returns = returns;
		this.orders = orders;
		this.userAddresses = userAddresses;
		this.userLogin = userLogin;
		this.carts = carts;
		this.returnRefunds = returnRefunds;
		this.paymentStatuses = paymentStatuses;
		this.orderHistories = orderHistories;
	}

	@Id

	@Column(name = "USER_ID", unique = true, nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "FIRST_NAME", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ID")
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "CONTACT_NUMBER", length = 10)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<Return> getReturns() {
		return this.returns;
	}

	public void setReturns(Set<Return> returns) {
		this.returns = returns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<UserAddress> getUserAddresses() {
		return this.userAddresses;
	}

	public void setUserAddresses(Set<UserAddress> userAddresses) {
		this.userAddresses = userAddresses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public UserLogin getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(UserLogin userLogin) {
		this.userLogin = userLogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<ReturnRefund> getReturnRefunds() {
		return this.returnRefunds;
	}

	public void setReturnRefunds(Set<ReturnRefund> returnRefunds) {
		this.returnRefunds = returnRefunds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<PaymentStatus> getPaymentStatuses() {
		return this.paymentStatuses;
	}

	public void setPaymentStatuses(Set<PaymentStatus> paymentStatuses) {
		this.paymentStatuses = paymentStatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<OrderHistory> getOrderHistories() {
		return this.orderHistories;
	}

	public void setOrderHistories(Set<OrderHistory> orderHistories) {
		this.orderHistories = orderHistories;
	}

}
