package com.tradeleaves.store.domain;
// Generated 27 Mar, 2016 3:29:16 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAddressId generated by hbm2java
 */
@Embeddable
public class UserAddressId implements java.io.Serializable {

	private String addressId;
	private String userId;

	public UserAddressId() {
	}

	public UserAddressId(String addressId, String userId) {
		this.addressId = addressId;
		this.userId = userId;
	}

	@Column(name = "ADDRESS_ID", nullable = false, length = 50)
	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	@Column(name = "USER_ID", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAddressId))
			return false;
		UserAddressId castOther = (UserAddressId) other;

		return ((this.getAddressId() == castOther.getAddressId()) || (this.getAddressId() != null
				&& castOther.getAddressId() != null && this.getAddressId().equals(castOther.getAddressId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAddressId() == null ? 0 : this.getAddressId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
